### ISSUE TITLE
Project checkpoint 3

### ISSUE THREAD

**Issue by esajdak** [esajdak/customCrafts#10]
@pawaitemadisoncollege

- Here is the current page using authentication (I know I probably should have a jsp in my browser url but I haven't gotten that far yet) http://18.217.148.113:8080/customCrafts/search.jsp (you'll need email "es@gmail.com" and password... "password" haha)
- After searching you should see the users (displaying data from database), I currently only have it set up as display all, so if you try searching something specific you're just going to get all the results for now.

**Comment by pawaitemadisoncollege** [comment]
Excellent! You are right on target - checkpoint 3 is done!
