### ISSUE TITLE
Week 9 exercise

### ISSUE THREAD

**Issue by esajdak** [esajdak/customCrafts#11]
@pawaitemadisoncollege
Implemented RESTful web service for user DAO, currently only for getAll()
http://localhost:8080/customCrafts_war/services/userSearch

**Comment by pawaitemadisoncollege** [comment]
Looks good @esajdak! 

You might consider skipping the use of controllers and calling right to a service like this from the front end. Angel is doing this in his project if you'd like a reference or to chat more about his experience incorporating this technique.
