### ISSUE TITLE
IndieProject Review

### ISSUE THREAD

**Issue by jeevarg** [esajdak/customCrafts#6]
# Design/Code Review 1

### Reviewer: Jeeva G

|Item |Considerations| Comments/Suggestions|
|--------|---------|---|
|||Reviewer comments and suggestions go here. Each item should have *at least* one "kudos" and two suggestions for improvement|
|**Problem Statement**|1. Accurately describes project purpose<br> 2. Is professional and free of typos, slang, etc.<br> 3. Fully explains the problem and the solution<br> 4. Is understandable by the average person| 1, 2, 3 - Problem statement is very precise and straight forward. No suggestions here. |
|**Design Documentation**|1. Navigation/flow through the application is logical and easy to use. <br>2. The order in which values are displayed are logical and easy to understand/use <br>3. The order in which the form fields entered are logical and easy to understand/use<br>4. All data discussed/documented (problem statement, flow, db design, etc.) is represented on the screens | 1 - could also implement one more page where users can look at their orders / items history. |
|**Data model/Database**|1. Everything on the screens and problem statement/flow is represented in the model <br> 2. There is at least one 1-to-many relationship.<br> 3. The model represents good database design <br>| 2 - missing javadocs on the Product entity contructors|
|**Code**|1. Proper Maven project structure is used<br> 2. a .gitignore file for IntelliJ Java projects has been implemented <br> 3. There is not any redundant or copy/paste code in the JSPs or classes<br> 4. Classes are appropriately-sized (no monster classes)<br> Property files are used appropriately: no hard-coded values <br> 5. Logging statements are used rather than System.out.println and printStackTrace.<br> 6. There are appropriate unit tests/code coverages.<br>| 1, 2, 4 - logging implemented and looks good. |

**Comment by pawaitemadisoncollege** [comment]
@jeevarg Did you find any printlns? If so, please indicate where so @esajdak  can easily fix them. If not, indicate none were found. Hint: the search feature is in Github can be useful for finding these.

**Comment by jeevarg** [comment]
Checked the entities, daos and tests for println statements. None were found.

**Comment by pawaitemadisoncollege** [comment]
@jeevarg and @esajdak  Looks like a couple sneaky ones here: 

![Screen Shot 2020-10-09 at 7 50 37 AM](https://user-images.githubusercontent.com/13874466/95585002-33321800-0a04-11eb-9c92-3f36ab33e234.png)

The screenshot also shows how to search for these through the entire repo.
