### ISSUE TITLE
Week 7 Ready

### ISSUE THREAD

**Issue by esajdak** [esajdak/customCrafts#9]
@pawaitemadisoncollege
I'm a little confused, in my web.xml if I use "userResults.jsp" I figured I should be able to go to /searchUser but it wouldn't allow you to go in until you sign in because it's forwarding that information to userResults? I couldn't quite figure out what the problem was there, but it works when I use "search.jsp" in my web.xml instead so I went with that for now for the purpose of this weeks exercise.

**Comment by pawaitemadisoncollege** [comment]
@esajdak Yep! You are exactly right, if userResults.jsp is "locked down", as soon as searchUser forwards to userResults.jsp, the user will need to authenticate.    As you continue working on your project, you will need to decide which roles can access which servlets and jsps, and then secure them appropriately.

**Comment by esajdak** [comment]
That didn't work though, I originally had userResults.jsp "locked down" and then went to localhost:8080/customCrafts/searchUser which should automatically forward- which it did but didn't require a sign in.. which was weird because I had no issues when switching to my search.jsp
I'm not sure I'll have to play with it a little more in the coming weeks and if I end up getting stuck I'll reach out.
